---
# This playbook builds and deploys server and client on specified ports on respective hosts

- hosts: compel
  vars:
    module_name: "compel-monitoring"
  tasks:
    - name: Deploy {{ module_name }}-server on compel 
      copy:
        src: ./bin/{{ module_name }}-server
        dest: ~/{{ module_name }}-server
        mode: "u+x"


    - name: Start {{ module_name }}-server on port {{server_port}}
      shell: ~/{{ module_name }}-server {{server_port}}
      changed_when: false
